### ISSUE TITLE
SHLOMIF_COMMON_SETUP makes Flatpak installation very awkward

### ISSUE THREAD

**Issue by ssokolow** [shlomif/shlomif-cmake-modules#1]
Currently, the `SHLOMIF_COMMON_SETUP` macro hard-codes the path `/usr/...` for a system install location for `Shlomif_Common.cmake` while `flatpak-builder` makes `/usr` the read-only location for the Runtime and expects application-specific dependencies to be installed in a parallel hierarchy under `/app`. (eg. `/app/share/...`)

Given that `flatpak-builder` also enforces that downloading and running downloaded code occur in separate phases to ensure reproducible builds, this has resulted in getting fc-solve to build to be the most frustrating, most time-consuming part I've yet encountered in trying to prepare PySolFC to be available on Flathub. (Though, to be fair, part of that is that CMake is a pain to someone who's only used to Python and Rust build systems and the occasional `./configure && make && checkinstall`.)

At the moment, i'm probably just going add a line to the flatpak-builder manifest to `.patch` the `/usr` line to `/app` in `Shlomif_Common.cmake` since that feels like it'd be easier for future maintainers to understand at a glance than trying to anticipate and pre-populate where it gets copied to.

(I'm already pinning a specific revision of this repository anyway, since the `flatpak-external-data-checker` metadata for automatically opening "bump dependencies" PRs seems to demand that `git` sources use tags to identify new releases available to be upgraded to.)

**Comment by shlomif** [comment]
On Thu, 22 Sep 2022 21:19:13 -0700
Stephan Sokolow ***@***.***> wrote:

> Currently, the `SHLOMIF_COMMON_SETUP` macro hard-codes the path `/usr/...`
> for a system install location for `Shlomif_Common.cmake` while
> `flatpak-builder` makes `/usr` the read-only location for the Runtime and
> expects application-specific dependencies to be installed in a parallel
> hierarchy under `/app`. (eg. `/app/share/...`)
> 
> Given that `flatpak-builder` also enforces that downloading and running
> downloaded code occur in separate phases to ensure reproducible builds, this
> has resulted in getting fc-solve to build to be the most frustrating, most
> time-consuming part I've yet encountered in trying to prepare PySolFC to be
> available on Flathub. (Though, to be fair, part of that is that CMake is a
> pain to someone who's only used to Python and Rust build systems.)
> 
> At the moment, i'm probably just going add a line to the flatpak-builder
> manifest to `.patch` the `/usr` line to `/app` in `Shlomif_Common.cmake`
> since that feels like it'd be easier for future maintainers to understand at
> a glance than trying to anticipate and pre-populate where it gets copied to.
> 

thx for the report - i'll take a look

-- 

Shlomi Fish       https://www.shlomifish.org/
Why I Love Perl - https://shlom.in/joy-of-perl

In Soviet Russia, cats own you. No, wait! Cats own you everywhere.

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
@ssokolow : please try with the latest changes.

**Comment by ssokolow** [comment]
Right now's not the best time for me, but I'll try to get to it soon.

**Comment by shlomif** [comment]
> Right now's not the best time for me, but I'll try to get to it soon.

@ssokolow : ping!

**Comment by ssokolow** [comment]
I'll see if I can take a look within the next week. Things are still up and down, but they've definitely improved.

**Comment by shlomif** [comment]
> I'll see if I can take a look within the next week. Things are still up and down, but they've definitely improved.

thanks!

**Comment by ssokolow** [comment]
I just went in to test things and, ouch, I forgot that, about a week and a half after opening this, I wound up reworking things to build from the solver tarballs, removing the need to interact with this directly in the PySolFC Flatpak build.

I can still test it if you want, but I may need another week or two to find a time slot since it'll essentially be rewriting a working `solver.json` module to pull from a different source via a different mechanism and introduce a new dependency.

**Comment by shlomif** [comment]
> I just went in to test things and, ouch, I forgot that, about a week and a half after opening this, I wound up reworking things to build from the solver tarballs, removing the need to interact with this directly in the PySolFC Flatpak build.
> 
> I can still test it if you want, but I may need another week or two to find a time slot since it'll essentially be rewriting a working `solver.json` module to pull from a different source via a different mechanism and introduce a new dependency.

please test it again, thanks

**Comment by ssokolow** [comment]
Sorry for going silent. This got buried under a bunch of other TODO tabs while I was looking for somewhere to fit it in and then forgotten until another bug I reported as part of making the PySolFC Flatpak got mentioned in my inbox. I'll try to get to it soon.

**Comment by shlomif** [comment]
On Sat, 09 Sep 2023 07:26:45 -0700
Stephan Sokolow ***@***.***> wrote:

> Sorry for going silent. This got buried under a bunch of other TODO tabs
> while I was looking for somewhere to fit it in and then forgotten until
> another bug I reported as part of making the PySolFC Flatpak got mentioned in
> my inbox. I'll try to get to it soon.
> 

thx4the update



-- 

Shlomi Fish       https://www.shlomifish.org/
https://ccmixter.org/files/destinazione_altrove/49997 - “Paint The Sky”

The more I think about it, the more I think I should think about it some more.
    — Clarissa Explains it All

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by ssokolow** [comment]
OK. Sorry for taking so flipping long. It's very frustrating when "Two steps forward, one step backward" on clearing out backlogged obligations grinds to a halt because things with deadlines keep jumping the queue.

You're now at the head of the queue for anything that isn't jumping it, and, aside from being a bit sleep-deprived, I should be able to give you my full attention at any time I'm awake from now until Christmas, barring an appointment on the 20th.

It appears this is fixed, since trying to do a naive build of fc-solve from source with this manifest fragment...

```
            "config-opts": [
                "-DFCS_WITH_TEST_SUITE=OFF",
                "-DCMAKE_MODULE_PATH=/app/share/cmake/Modules",
                "-DSHLOMIF_SYSTEM_INSTALL_DIR=/app/share/cmake/Modules"
            ],
```

...now dies when the `IF (NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${pats_dir}")` block  in `fc-solve/fc-solve/source/CMakeLists.txt` runs into how flatpak-builder sandboxes away network access in the build phase for reproducibility.

I'll let you decide whether this issue is resolved or whether there's anything else you want me to check first.

**Comment by shlomif** [comment]
@ssokolow : thanks4the update. I think I'll close this issue4now [it can be reopened later]
